### PR TITLE
[WIP] implement basic CSS theming

### PR DESCRIPTION
**Pull request by MovingtoMars**

### CODE REVIEW

**Comment by jackpot51** [comment]
Is this ready for merge?

**Comment by MovingtoMars** [comment]
Well the two things missing right now would be
- selectors based on ancestor/sibling elements
- value caching

Both of which would require breaking changes in `Value`. So it depends on if you want to just merge this now and do that later, or do it all at the same time.

I'm not sure on the best way of doing both of those things though. I have some ideas but I need to discuss them first!

**Comment by MovingtoMars** [comment]
Follow-up post:
I see two approaches to anestor/sibling elements:

1. Each widget stores an `Arc<Widget>` of its parent. Add `fn parent(&self) -> Arc<Widget>` and `fn children<&self> -> Arc<Widget>` to the `Widget` trait.

2. We have `SelectorQuery` that we pass around to `Widget.draw()`. As we pass it down the hierarchy, we push on elements like a stack, to build up the DOM.


Another thing that could be helpful is a `WidgetWrapper` type that handles data/behaviour common to all widgets. This would be useful for caching, adding arbitrary CSS classes, storing parent widgets, etc.

```
WidgetHandle {
    widget: Arc<Widget>,
    classes: HashSet<String>,
    parent: Option<Arc<Widget>>,
    dirty: bool,
    ...
}

impl DerefMut for WidgetHandle {
    fn deref_mut(&self) -> &mut Widget {
        self.dirty = true; // need to rebuild cache
        &*self.widget
    }
}
```

**Comment by pharaone** [comment]
infos?

**Comment by pharaone** [comment]
@MovingtoMars news about this?

**Comment by MovingtoMars** [comment]
The basic functionality works, however the unresolved problems I mentioned in my comments are still there.

It's really up to the maintainers if they want to merge this as-is, or not merge until more work is done.

@jackpot51

**Comment by jackpot51** [comment]
I have decided to merge this and work to improve it.

**Pull request merged**
