### PR TITLE
OrbTK Documentation update (V2)

### PR DESCRIPTION
**Pull request by rzerres**
# documentation updates

* rebase on new structure (#448)
* include commits as documentation updates per submodule

## Contribution checklist:
- [x] Add [documentation](https://doc.rust-lang.org/1.7.0/book/documentation.html) to all public structs, traits and functions.
- [x] Run `cargo fmt` to make the formatting consistent across the codebase
- [x] Run `cargo clippy` to check with the linter

### CODE REVIEW

**Comment by ghost** [comment]
Thank you

**Comment by rzerres** [comment]
With commit 8af3937 i have finished to document all public functions beside the modules and structs. This does not imply, that we can't add more desciptive text or example code. But with the given status it should be good enough for the initial version. 

I am confident, that this will make it quite more easy to keep up to date documentation for any upcoming PR merges.

**Comment by rzerres** [comment]
since this is my wip branch to track just documentation updates, linter and clippy byte us for new Rust 2021.
Therefore i included the tiny bug fixes 

* assert!() calls
* unneeded borrow checker calls

Please cherry pick to develop branch ....

**Comment by rzerres** [comment]
Merged

**Pull request closed without merging**
