### PR TITLE
Material design icons - integration

### PR DESCRIPTION
**Pull request by rzerres**
# Version History

## Version 1
* initial pull request used as a RFC

## Version 2
* Brake open the relavent pieces in comparison to version 1.
Since this is already in the developmant branch, this one did rebase the commits. It should help to ease the review.

## Version 3
* incorporate a python script to generate all glyphs and corresponding static consts from a  baseline.css.
* all icons are now available
* update the code to make use of all available Material-Icons font names
* update the core widgets code to reference correct font and glyph constant
* update example widgets code to make use of new material-icons-font
* cleanup the documentation part
* include the glyph constant file

# Material Design Icons
Since the Google Code doesen't see any updates anymore, the is this OS Github project, that has taken over and improved quite a bit. Beside the woff2 support, they also cleaned up the other font variants.
While digging into it, i did realize, that the usage of icon fonts in general is depreciated in a longer run. All major platforms are now support SVG's much better over the last years. So we might be able to just rely on SVG-Icons.
Nevertheless, having an up to date icon font available will be handy inside the Toolkit.

## Glyph Integration
The new Glyphs are are coded as codepoints, and not as single characters. These codepoints are common inside the ttf and the woff2 variants. As a consequence just one rust mapping code is needed. More documentation is placed inside the source code. You can view the Glyphs and its parameters quite nicely with FontForge.

## Testing
To verify the correct handling, example source of 'widgets.rs' has been updated to use the new font and new Glyphs. API code for the core "check_box" and "combo_box" widgets have been adopted as well. The code-base compiles it without errors. Glyphs are rendered as expected.

best regards
Ralf

### CODE REVIEW

**Comment by FloVanGH** [comment]
I've added the base line wof font to the window_adapter (api crate). And used one of the base line glyphs. Unfortunately the icon is not displayed. The current backend that is used to diplay font glpyhs is RustType https://crates.io/crates/rusttype. I checked it and apparently it supports only ttf and otf 🙈. We need RustType because it also supports Redox.

**Comment by rzerres** [comment]
> I've added the base line wof font to the window_adapter (api crate). And used one of the base line glyphs. Unfortunately the icon is not displayed. The current backend that is used to diplay font glpyhs is RustType https://crates.io/crates/rusttype. I checked it and apparently it supports only ttf and otf see_no_evil. We need RustType because it also supports Redox.

I don't know, if it is worth a try to ask woff2 integration in rusttype. TTF is working by now. Woff2 might help in terms of speed and the amount of data that need to be transfered (e.g. --target browser). 
When i read about fonthandling i got the image, SVG is on its way for global uses. If we have can address the SVG-Icon in .icon directly (e.g. just using the MD_* name) we get best out of both worlds? The icons are available from the Material-Icons orign as well....

**Comment by FloVanGH** [comment]
> I don't know, if it is worth a try to ask for woff2 integration in rusttype.

russtype has now a successor project but it does also not include woff2. 

SVG rendering should be possible but I have experiment with it in OrbTk. I think it could be a great alternative for the icon fonts.

**Comment by rzerres** [comment]
> SVG rendering should be possible

Fine. Let me know, if i can help on that. Right now i need to conentrate an the app ....

**Review by rzerres — COMMENTED** [review]
Updated next charge of Glyphs.
All MD_A* glyphs from the font are incorporated. Next updates will proceed with section MD_B*

**Comment by rzerres** [comment]
Hey, 
this PR is continued with commits incorporting icons for Letter "B" and "C". will contiune with the next letters if time and courage will let me go ....

**Comment by rzerres** [comment]
Here are
the continued Glyphs commits incorporating icons for Letter "D" and "E". will contiune with the next letters if time and courage will let me go ....

**Comment by rzerres** [comment]
## Update Version 3

michal w. sieron <michalwsieron@gmail.com> took over the final job. He wrote a python script (gist url in source),
that is taking fonts baseline.css and generates the needed const variable beside the rust readable uni-codes.

## Usage
Since the glyphs have the same codepoints in all 'Material _Icons' fonts, we don't need seperate source files to describe the variants. Commit 6535191 is taking care to clean up the code base.

To use the varients/different look in orbtk, just adjust the font name. The const (MD_<icon_name>) will be the same.

**Comment by FloVanGH** [comment]
@rzerres is there a file missing? `material_icons_font.rs`?

**Comment by rzerres** [comment]
@FloVanGH sometimes it is git magic. Don't know, why the file was missing. I could see it in my local branch so ...

**Comment by FloVanGH** [comment]
Thank you!!!

**Pull request merged**
