### PR TITLE
[WIP] Multiline support forTextBox widget

### PR DESCRIPTION
**Pull request by rzerres**
# Context:
Enhance the TextBox widget to support multi line input

## Contribution checklist:
- [x] Add [documentation](https://doc.rust-lang.org/1.7.0/book/documentation.html) to all public structs, traits and functions.
- [x] Add unit tests if possible
- [x] Describe the major change(s) in the CHANGELOG.MD
- [x] Run `cargo fmt` to make the formatting consistent across the codebase
- [x] Run `cargo clippy` to check with the linter

## Status
With the given RFC, you can separate lines in a TextBox widget. Typing "Ctrl+Enter" while you edit the content of the given TextBox will insert a '\n'.
I tested with raqote renderer. It will recognize the insertet '\n' and split the line as expected. Never the less, cursor handling is broken. And i haven't made any attempts to get the constraints of the TextBox right. 

## Further work needed
Adaption needs to aggree on a concept will solve the following topics

- [ ] auto resize the widget size of the TextBox (up to the defined max_height)
- [ ] enable a Scroll-Indicator if line number gets bigger than the number visible lines inside the TextBox
- [ ] respect the definition of an initial height / size

### CODE REVIEW

**Comment by FloVanGH** [comment]
You are working on multiline text input that's great 🙂

**Comment by kivimango** [comment]
According to docs, the TextBox is a single line text input widget. I think you should add a boolean `wrap_lines`  property to keep the original behavior just in case. Or it could be extracted to a separate TextArea widget.

**Comment by rzerres** [comment]
I changed this PR to be Draft mode. 
@kivimango  good point. I don't have the time to dig further into this issue. So if anyone has time and pacience ... feel free improve and send commits.

**Comment by rzerres** [comment]
> I think you should add a boolean `wrap_lines` property to keep the original behavior just in case.

Your suggestion is implemented as property `line_wrap`. 
I updated `PasswordBox` code, to include this property with defaulting to `false`. In that way, passwords are only entered in a one liner :)

**Comment by rzerres** [comment]
This Draft is superseeded by #449

**Pull request closed without merging**
