### PR TITLE
Text behavior

### PR DESCRIPTION
**Pull request by kivimango**
#275
This PR attempts to extract common text widget related logic into a new widget called TextBehavior to share the same functionality over different text widgets and to avoid code duplication.

### CODE REVIEW

**Comment by FloVanGH** [comment]
I think I have to do the merge manually. I have done some fixes on the text handling before your PR. And in your PR there is a problem with the style state management. e.g. the empty state has the false color. 

Thank you. The extraction will be benefit by creating new text input based widgets.

**Comment by kivimango** [comment]
I would do it myself, but I'm afraid of making an even bigger mess and I never resolved conflicts before.
I see that imports changed and some code in the map_chars_index_to_position().

**Comment by FloVanGH** [comment]
I really like your documentation!

**Comment by FloVanGH** [comment]
It's now manual merged, thank you!

**Pull request closed without merging**
