### PR TITLE
Document expressions

### PR DESCRIPTION
**Pull request by sandmor**
# Context:
This PR documents the use of expressions and how they can be used in themes to define gradients, also `colors.txt` was prettified in my adventure learning neovim(vim).

### CODE REVIEW

**Comment by rzerres** [comment]
@sandmor you do reference 'TAU' in your code. This constant isn't available in rust stable.
Could you please adapt the code? You will finde a working reference in 

# crates/render/src/common.rs
```
4:pub const TAU: f64 = 6.283_185_307_179_586_f64;
```

**Comment by sandmor** [comment]
Nope, it was stabilized in the last rust version you need to run `rustup update stable` also `OrbTk` already uses it on `crates/render/src/common.rs`.

**Comment by rzerres** [comment]
> Nope, it was stabilized in the last rust version you need to run `rustup update stable` also `OrbTk` already uses it on `crates/render/src/common.rs`.

Thats right, but there it is defined inside the crate. not from the std liberary, right?
My rustc 1.45.2 (stable) with the latest std doesn't accept a TAU.

**Comment by sandmor** [comment]
Whoops, where did that come from? I just do that PR a couple of days ago and I used the std lib TAU, well okay...

**Comment by sandmor** [comment]
@rzerres Thank you!

**Comment by rzerres** [comment]
@sandmor de rien!

**Comment by sandmor** [comment]
Okay, google translate me that!

**Comment by FloVanGH** [comment]
looks good to me thank you.

**Pull request merged**
