### PR TITLE
reformat files with rustfmt

### PR DESCRIPTION
**Pull request by vadixidav**

### CODE REVIEW

**Comment by jackpot51** [comment]
I do not merge automatic formatting, it creates too much history noise.

**Comment by vadixidav** [comment]
Would you like if I submitted a PR for each file?

**Comment by jackpot51** [comment]
No, it borks the git history for any lines that are formatted, I do not want it

**Comment by vadixidav** [comment]
Okay, I understand. What if every commit from the beginning was cherry picked and amended with rustfmt changes so all history was preserved?

**Pull request closed without merging**
