### PR TITLE
fix compile on m1 mac

### PR DESCRIPTION
**Pull request by HanYunChenLuo**
# Context:
fix compile on m1 mac.

### CODE REVIEW

**Comment by jackpot51** [comment]
This should be fixed already if you do a `cargo update` and pull the latest `orbclient`

**Comment by HanYunChenLuo** [comment]
> This should be fixed already if you do a `cargo update` and pull the latest `orbclient`

I Just do the action you mentioned. But still has a error with log below. this commit is for this error.

  = note: Undefined symbols for architecture x86_64:
            "_CHHapticDynamicParameterIDHapticIntensityControl", referenced from:
                -[SDL_RumbleMotor setIntensity:] in libsdl2_sys-d99d3cb13bd69586.rlib(SDL_mfijoystick.m.o)
            "_CHHapticEventParameterIDHapticIntensity", referenced from:
                -[SDL_RumbleMotor setIntensity:] in libsdl2_sys-d99d3cb13bd69586.rlib(SDL_mfijoystick.m.o)
            "_CHHapticEventTypeHapticContinuous", referenced from:
                -[SDL_RumbleMotor setIntensity:] in libsdl2_sys-d99d3cb13bd69586.rlib(SDL_mfijoystick.m.o)
            "_OBJC_CLASS_$_CHHapticDynamicParameter", referenced from:
                objc-class-ref in libsdl2_sys-d99d3cb13bd69586.rlib(SDL_mfijoystick.m.o)
            "_OBJC_CLASS_$_CHHapticEvent", referenced from:
                objc-class-ref in libsdl2_sys-d99d3cb13bd69586.rlib(SDL_mfijoystick.m.o)
            "_OBJC_CLASS_$_CHHapticEventParameter", referenced from:
                objc-class-ref in libsdl2_sys-d99d3cb13bd69586.rlib(SDL_mfijoystick.m.o)
            "_OBJC_CLASS_$_CHHapticPattern", referenced from:
                objc-class-ref in libsdl2_sys-d99d3cb13bd69586.rlib(SDL_mfijoystick.m.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: could not compile `orbtk` due to previous error

**Comment by jackpot51** [comment]
Please try a `cargo update` again. orbclient should be at version 0.3.35 to have the fix.

**Comment by hardBSDk** [comment]
Redox moved to GitLab years ago, thus if you still want to merge it, move this pull request to there.

If you still want to contribute to Redox, talk with us in the [Matrix chat](https://matrix.to/#/#redox:matrix.org).

**Pull request closed without merging**
